### ISSUE TITLE
Preview while usb printing ?

### ISSUE THREAD

**Issue by didli** [KenHuffman/UltimakerCuraScripts#5]
Hi, using latest Cura (appimage) on Linux and an Ender 3 v2 Neo, the plugin works great so thank you for your script !
Now do you think there could be a way to get the preview while printing directly from USB ?

**Comment by KenHuffman** [comment]
@didli If you use OctoPrint to print by USB, I've also updated the [OctoPrint-PrusaSlicerThumbnails](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails) plugin to display these embedded images in the Creality Ender-3 V2 Neo format.

This will be in version 1.0.2, but at the moment 1.0.1 is still the official release, but if you go to **OctoPrint Settings -> Software Update -> Slicer Thumbnails -> Release Channel** and select **Release Candidate** you get a version that work great.
